[package]
name = "bbx_sandbox"
version = "0.1.0"
edition = "2024"

[dependencies]
bbx_dsp = { path = "../bbx_dsp" }
bbx_file = { path = "../bbx_file" }
bbx_midi = { path = "../bbx_midi" }

rand = "0.8.5"
rodio = "0.20.1"
