[package]
name = "bbx_sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
bbx_dsp = { path = "../bbx_dsp" }
bbx_file = { path = "../bbx_file" }
bbx_midi = { path = "../bbx_midi" }

rodio = "0.20.1"
