[package]
name = "bbx_sandbox"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
bbx_dsp.workspace = true
bbx_file.workspace = true
bbx_midi = { workspace = true, features = ["streaming"] }
rand.workspace = true
rodio.workspace = true
