[package]
name = "bbx_dsp"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
bbx_core = { path = "../bbx_core" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.146"

[build-dependencies]
cbindgen = "0.29.2"
