name: Clippy

on:
    pull_request:
    push:
        branches: [main, develop]

jobs:
    lint:
        name: Cargo Clippy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup Linux Dependencies
              run: sudo apt install alsa libasound2-dev libssl-dev pkg-config

            - name: Setup Rust
              uses: dtolnay/rust-toolchain@master
              with:
                  toolchain: nightly-2025-06-08
                  components: clippy

            - name: Cargo Clippy
              run: cargo clippy